---
- hosts: all
  tasks:
    - name: copy requirements file
      copy:
        src: ./requirements.txt
        dest: /home/eitn30-pi/requirements.txt
    - name: adafruit packages
      pip:
        requirements: /home/eitn30-pi/requirements.txt
        state: present
      become: True
...
