---
  - name: copy requirements file
    copy:
      src: requirements.txt
      dest: /home/eitn30-pi/requirements.txt
  - name: adafruit packages
    pip:
      requirements: /home/eitn30-pi/requirements.txt
      state: present
    become: True
  - name: copy lora test files
    copy:
      src: "{{ item  }}"
      dest: /home/eitn30-pi/lora_python/
    with_fileglob:
      - "*.py"
...
